# Import

In [1]:
import numpy as np
import pandas as pd

# 배열 정보 확인

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(a1.size)
print(a1.itemsize)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64
5
8


In [3]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 2], a2[2, 2])
print(a2.ndim)
print(a2.dtype)
print(a2.size)
print(a2.itemsize)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
1 6 9
2
int64
12
8


# 특수 배열 생성

In [4]:
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
print(np.ones((3, 3)))
print(np.full((3, 3), 3.14)) # fill with 3.14

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [6]:
print(np.eye(3)) # Identity matrix
print(np.tri(3)) # Lower triangular matrix
print(np.empty(10)) # uninitialized array. faster than np.zeros

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
print(a1)
print(np.zeros_like(a1))
print(a2)
print(np.ones_like(a2))

[1 2 3 4 5]
[0 0 0 0 0]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
print(np.arange(0, 30, 2)) # start, end, step
print(np.linspace(0, 1, 5)) # 5 numbers from 0 to 1
print(np.logspace(1, 5, 5)) # 10^1, 10^2, 10^3, 10^4, 10^5

print(a1.astype(np.int64))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[0.   0.25 0.5  0.75 1.  ]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
[1 2 3 4 5]


# 랜덤 배열 생성

In [9]:
print(np.random.random((3, 3))) # uniform distribution
print(np.random.randint(0, 10, (3, 3))) # uniform distribution
print(np.random.normal(0, 1, (3, 3))) # normal distribution
print(np.random.randn(3, 3)) # uniform distribution
print(np.random.randn(3, 3)) # standard normal distribution

[[0.95240739 0.59275406 0.80246441]
 [0.9473915  0.55325548 0.87415295]
 [0.92763191 0.52618009 0.41852187]]
[[5 1 5]
 [8 7 2]
 [0 9 8]]
[[-0.56378952 -0.65589458 -0.72453763]
 [-0.647676    2.56396803  1.03612659]
 [ 1.27934173  0.14206992  1.28410583]]
[[-1.14754663 -0.28997106  0.01031383]
 [ 0.89927599 -0.49320516  1.52021204]
 [-0.20507256 -0.39683909 -1.26806269]]
[[ 0.89221811 -1.17820632 -0.49611002]
 [-2.13862114  0.34102486 -1.73090844]
 [-0.7186544  -0.18680428 -0.56880947]]


# 배열 수정

In [10]:
print(a2.T) # transpose
print(a2.swapaxes(0, 1)) # swap axes

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [11]:
print(a1)
a1 = np.insert(a1, 5, 10)
a1

[1 2 3 4 5]


array([ 1,  2,  3,  4,  5, 10])

In [12]:
a1.reshape(2, 3)

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [13]:
a1.resize(3, 2) # resize is in-placed.
print(a1)

[[ 1  2]
 [ 3  4]
 [ 5 10]]


# 배열 인덱싱, 슬라이싱

In [14]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
print(a3[2, 2, 2])
print(a3[1, 1, -1])

9
6


In [16]:
print(a2)
print(a2[1])
print(a2[1, 1:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[4 5 6]
[5 6]


In [17]:
print(a2[:2, :2])
print(a2[:2, ::-1])

[[1 2]
 [4 5]]
[[3 2 1]
 [6 5 4]]


In [18]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
bi = [True, False, True, False, True]
print(a1[bi]) # boolean indexing

fi = [0, 2]
print(a1[fi]) # fancy indexing
# slicing의 step보다 자유도가 높은 방법

[1 2 3 4 5]
[1 3 5]
[1 3]


# 배열 원소 삭제

In [19]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)

[1 2 3 4 5]
[1 3 4 5]


In [20]:
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
b1 = np.delete(a2, 1, axis=0)
print(b1)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [22]:
b1 = np.delete(a2, 1, axis=1)
print(b1)

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


# 배열 복사

In [23]:
a = np.array([1, 2, 3, 4])
b = a[1:3]
print(b)
b[0] = 100
print(b)
print(a) 
# 중요: Numpy Array의 slicing은 copy가 안됨

[2 3]
[100   3]
[  1 100   3   4]


In [24]:
a = np.array([1, 2, 3, 4])
b = a[1:3].copy()
print(b)
b[0] = 100
print(b)
print(a)

[2 3]
[100   3]
[1 2 3 4]


# 배열 수정2

In [25]:
a2 = np.arange(1, 10).reshape(3, 3)
b2 = np.arange(11, 20).reshape(3, 3)

In [26]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [28]:
c2 = np.append(a2, b2)
c2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [29]:
c2 = np.append(a2, b2, axis=0)
c2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [30]:
c2 = np.append(a2, b2, axis=1)
c2

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [31]:
np.vstack([a2, b2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [32]:
np.hstack([a2, b2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [33]:
a1

array([1, 2, 3, 4, 5])

In [34]:
b1, c1 = np.split(a1, [2])
b1, c1

(array([1, 2]), array([3, 4, 5]))

In [35]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
b2, c2 = np.vsplit(a2, [2])
b2, c2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]))

In [37]:
b2, c2 = np.hsplit(a2, [2])
b2, c2

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]]))

# Brodcasting

In [38]:
a = np.array([1, 2, 3])
b = 2
a * b

array([2, 4, 6])

In [39]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [40]:
a = np.array([0, 10, 20, 40]).reshape(4, 1)
b = np.array([1, 2, 3])
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [41, 42, 43]])

# 산술

In [41]:
a1 = np.array([1, 3])
print(a1)
print(np.add(a1, 1))
print(np.subtract(a1, 1))
print(np.negative(a1))
print(np.multiply(a1, 2))
print(np.divide(a1, 2))
print(np.mod(a1, 2))
print(np.floor_divide(a1, 2))
print(np.power(a1, 2))

[1 3]
[2 4]
[0 2]
[-1 -3]
[2 6]
[0.5 1.5]
[1 1]
[0 1]
[1 9]


# 절대값

In [42]:
a1 = np.array([1, -2, 3, -4])
print(np.absolute(a1))
print(np.abs(a1))

[1 2 3 4]
[1 2 3 4]


# 지수, 로그함수

In [43]:
a1 = np.array([1, 2, 3, 4])
print(np.square(a1))
print(np.sqrt(a1))
print(np.power(a1, 3))
print(np.exp(a1))
print(np.exp2(a1))
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 1  8 27 64]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 2.  4.  8. 16.]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


# 삼각함수

In [44]:
t = np.deg2rad(45)
print(t)
print(np.rad2deg(t))
a1 = np.array([0, 1, 2, 3, t])
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))
print(np.arctan(a1))

0.7853981633974483
45.0
[0.         0.84147098 0.90929743 0.14112001 0.70710678]
[ 1.          0.54030231 -0.41614684 -0.9899925   0.70710678]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.        ]
[0.         0.78539816 1.10714872 1.24904577 0.66577375]


# 집계 함수

In [45]:
a1 = np.array([[1, 2], [3, 4]])
print(a1.sum(), np.sum(a1))
print(a1.sum(axis=0), np.sum(a1, axis=0)) # column
print(a1.sum(axis=1), np.sum(a1, axis=1)) # row


10 10
[4 6] [4 6]
[3 7] [3 7]


In [46]:

print(np.cumsum(a1)) # cumulative sum
print(np.cumsum(a1, axis=0))
print(np.cumsum(a1, axis=1))


[ 1  3  6 10]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [47]:

a1 = np.array([[1, 3, 10], [5, 12, 6], [7, 5, 100]])
print(np.diff(a1))
print(np.prod(a1))
print(np.cumprod(a1))
b1 = np.ones_like(a1)
print(np.dot(a1, b1))


[[ 2  7]
 [ 7 -6]
 [-2 95]]
37800000
[       1        3       30      150     1800    10800    75600   378000
 37800000]
[[ 14  14  14]
 [ 23  23  23]
 [112 112 112]]


In [48]:
print(np.mean(a1))
print(np.median(a1))
print(np.average(a1))
print(np.std(a1))
print(np.var(a1))
print(np.min(a1))
print(np.max(a1))
print(np.argmin(a1))
print(np.argmax(a1))

16.555555555555557
6.0
16.555555555555557
29.66895538404153
880.246913580247
1
100
0
8


In [49]:
a1 = np.array([[False, True, True],
               [False, True, False],
               [False, False, False]])
print(a1)
print(np.any(a1))
print(np.all(a1))

print(np.all(a1, axis=0))
print(np.all(a1, axis=1))

print(np.any(a1, axis=0))
print(np.any(a1, axis=1))

[[False  True  True]
 [False  True False]
 [False False False]]
True
False
[False False False]
[False False False]
[False  True  True]
[ True  True False]


# 비교

In [50]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(a1 == 2)
print(a1 != 2)
print(a1 > 2)
print(a1 >= 2)
print(a1 < 2)
print(a1 <= 2)

[1 2 3 4 5]
[False  True False False False]
[ True False  True  True  True]
[False False  True  True  True]
[False  True  True  True  True]
[ True False False False False]
[ True  True False False False]


# Boolean

In [51]:
a1 = np.arange(1, 10).reshape(3, 3)
print(a1)
print((a1 > 2) & (a1 < 7))
print(a1[(a1 > 2) & (a1 < 7)])

print((a1 > 2) | (a1 < 7))
print(a1[(a1 > 2) | (a1 < 7)])

print((a1 > 2) ^ (a1 < 7))
print(a1[(a1 > 2) ^ (a1 < 7)])

print(~(a1 > 2))
print(a1[~(a1 > 2)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False  True]
 [ True  True  True]
 [False False False]]
[3 4 5 6]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True False]
 [False False False]
 [ True  True  True]]
[1 2 7 8 9]
[[ True  True False]
 [False False False]
 [False False False]]
[1 2]


# 정렬

In [52]:
np.random.seed(20221186)
a1 = np.random.randint(1, 10, size=10)

print(a1)
print(np.sort(a1)) # not inplace
print(a1)
print(np.argsort(a1))
print(a1.sort()) # inplace
print(a1)

[7 2 9 8 8 2 8 8 9 1]
[1 2 2 7 8 8 8 8 9 9]
[7 2 9 8 8 2 8 8 9 1]
[9 1 5 0 3 4 6 7 2 8]
None
[1 2 2 7 8 8 8 8 9 9]


# 입출력

In [53]:
a1 = np.random.randint(1, 10, size=10)
b1 = np.random.randint(1, 10, size=10)

print(a1)
print(b1)

np.save('a', a1)
np.savez('ab', a1, b1)
!ls

[7 9 6 4 7 8 1 5 6 8]
[3 9 4 7 3 1 8 6 5 5]
AI                    H10_2.c               a.npy
C_NoteBook            JupyterNotebook.ipynb ab.npz
C_NoteBook.c          NoteBook.hs           english_word.csv
Cpp_NoteBook.cpp      NoteBook.py           in.txt
FILE1.txt             PS                    np_notebook.ipynb
H10_1                 README.md             pd_notebook.ipynb
H10_1.c               Shocking-Things       tempCodeRunnerFile.py


In [54]:
a2 = np.load('a.npy')
print(a2)
ab2 = np.load('ab.npz')

print(ab2)
print(ab2.files)

print(ab2['arr_0'])
print(ab2['arr_1'])

np.savetxt('a.csv', a2, delimiter=',')
!ls
!cat a.csv
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[7 9 6 4 7 8 1 5 6 8]
['arr_0', 'arr_1']
[7 9 6 4 7 8 1 5 6 8]
[3 9 4 7 3 1 8 6 5 5]
AI                    JupyterNotebook.ipynb ab.npz
C_NoteBook            NoteBook.hs           english_word.csv
C_NoteBook.c          NoteBook.py           in.txt
Cpp_NoteBook.cpp      PS                    np_notebook.ipynb
FILE1.txt             README.md             pd_notebook.ipynb
H10_1                 Shocking-Things       tempCodeRunnerFile.py
H10_1.c               a.csv
H10_2.c               a.npy
7.000000000000000000e+00
9.000000000000000000e+00
6.000000000000000000e+00
4.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00
1.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
8.000000000000000000e+00
[7. 9. 6. 4. 7. 8. 1. 5. 6. 8.]
