# Import

In [127]:
import numpy as np
import pandas as pd

# 배열 정보 확인

In [128]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(a1.size)
print(a1.itemsize)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64
5
8


In [129]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 2], a2[2, 2])
print(a2.ndim)
print(a2.dtype)
print(a2.size)
print(a2.itemsize)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
1 6 9
2
int64
12
8


# 특수 배열 생성

In [130]:
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [131]:
print(np.ones((3, 3)))
print(np.full((3, 3), 3.14)) # fill with 3.14

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [132]:
print(np.eye(3)) # Identity matrix
print(np.tri(3)) # Lower triangular matrix
print(np.empty(10)) # uninitialized array. faster than np.zeros

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [133]:
print(a1)
print(np.zeros_like(a1))
print(a2)
print(np.ones_like(a2))

[1 2 3 4 5]
[0 0 0 0 0]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [134]:
print(np.arange(0, 30, 2)) # start, end, step
print(np.linspace(0, 1, 5)) # 5 numbers from 0 to 1
print(np.logspace(1, 5, 5)) # 10^1, 10^2, 10^3, 10^4, 10^5

print(a1.astype(np.int64))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[0.   0.25 0.5  0.75 1.  ]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
[1 2 3 4 5]


# 랜덤 배열 생성

In [135]:
print(np.random.random((3, 3))) # uniform distribution
print(np.random.randint(0, 10, (3, 3))) # uniform distribution
print(np.random.normal(0, 1, (3, 3))) # normal distribution
print(np.random.randn(3, 3)) # uniform distribution
print(np.random.randn(3, 3)) # standard normal distribution

[[0.72414492 0.35774282 0.18357584]
 [0.29967196 0.47787882 0.97379079]
 [0.57735279 0.34389627 0.9217013 ]]
[[4 9 9]
 [4 1 7]
 [4 8 6]]
[[ 0.85138678  0.15111507  1.01961506]
 [ 1.75466429 -1.31363929  0.97337722]
 [ 0.53904486  0.87373849  0.29237028]]
[[ 1.29035796 -1.48048798  0.67811145]
 [ 0.66517204  1.39149855  0.37621858]
 [ 0.5190072   0.62194921  2.32553074]]
[[ 0.14362361  1.31911047 -0.13311154]
 [-0.25394988 -0.8974996  -0.25953282]
 [ 1.45430648 -0.72930244  1.59194358]]


# 배열 수정

In [136]:
print(a2.T) # transpose
print(a2.swapaxes(0, 1)) # swap axes

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [137]:
print(a1)
a1 = np.insert(a1, 5, 10)
a1

[1 2 3 4 5]


array([ 1,  2,  3,  4,  5, 10])

In [138]:
a1.reshape(2, 3)

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [139]:
a1.resize(3, 2) # resize is in-placed.
print(a1)

[[ 1  2]
 [ 3  4]
 [ 5 10]]


# 배열 인덱싱, 슬라이싱

In [140]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [141]:
print(a3[2, 2, 2])
print(a3[1, 1, -1])

9
6


In [142]:
print(a2)
print(a2[1])
print(a2[1, 1:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[4 5 6]
[5 6]


In [143]:
print(a2[:2, :2])
print(a2[:2, ::-1])

[[1 2]
 [4 5]]
[[3 2 1]
 [6 5 4]]


In [144]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
bi = [True, False, True, False, True]
print(a1[bi]) # boolean indexing

fi = [0, 2]
print(a1[fi]) # fancy indexing
# slicing의 step보다 자유도가 높은 방법

[1 2 3 4 5]
[1 3 5]
[1 3]


# 배열 원소 삭제

In [145]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)

[1 2 3 4 5]
[1 3 4 5]


In [146]:
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [147]:
b1 = np.delete(a2, 1, axis=0)
print(b1)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [148]:
b1 = np.delete(a2, 1, axis=1)
print(b1)

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


# 배열 복사

In [149]:
a = np.array([1, 2, 3, 4])
b = a[1:3]
print(b)
b[0] = 100
print(b)
print(a) 
# 중요: Numpy Array의 slicing은 copy가 안됨

[2 3]
[100   3]
[  1 100   3   4]


In [150]:
a = np.array([1, 2, 3, 4])
b = a[1:3].copy()
print(b)
b[0] = 100
print(b)
print(a)

[2 3]
[100   3]
[1 2 3 4]


# 배열 수정2

In [151]:
a2 = np.arange(1, 10).reshape(3, 3)
b2 = np.arange(11, 20).reshape(3, 3)

In [152]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
b2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [154]:
c2 = np.append(a2, b2)
c2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [155]:
c2 = np.append(a2, b2, axis=0)
c2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [156]:
c2 = np.append(a2, b2, axis=1)
c2

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [157]:
np.vstack([a2, b2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [158]:
np.hstack([a2, b2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [159]:
a1

array([1, 2, 3, 4, 5])

In [160]:
b1, c1 = np.split(a1, [2])
b1, c1

(array([1, 2]), array([3, 4, 5]))

In [161]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
b2, c2 = np.vsplit(a2, [2])
b2, c2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]))

In [163]:
b2, c2 = np.hsplit(a2, [2])
b2, c2

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]]))

# Brodcasting

In [164]:
a = np.array([1, 2, 3])
b = 2
a * b

array([2, 4, 6])

In [165]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [166]:
a = np.array([0, 10, 20, 40]).reshape(4, 1)
b = np.array([1, 2, 3])
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [41, 42, 43]])